name: balacify
description: "Smart AI-powered calorie-tracking app with modern architecture"
publish_to: none
version: 2.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core packages
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_messaging: ^15.2.10
  firebase_analytics: ^11.6.0
  
  # Network
  http: ^1.2.2
  dio: ^5.7.0
  connectivity_plus: ^6.1.5
  
  # AI/ML
  google_generative_ai: ^0.4.7
  
  # Auth
  google_sign_in: ^7.2.0
  
  # Images & Media
  image_picker: ^1.1.2
  image: ^4.1.3
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.4.1
  
  # UI/UX
  google_fonts: ^6.3.2
  flutter_animate: ^4.5.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  fl_chart: ^0.69.2
  percent_indicator: ^4.2.4
  
  # Utils
  intl: ^0.20.2
  timeago: ^3.7.0
  path_provider: ^2.1.4
  permission_handler: ^11.4.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  device_info_plus: ^10.1.2
  package_info_plus: ^8.3.1
  shared_preferences: ^2.3.2
  
  # Architecture
  json_annotation: ^4.9.0
  formz: ^0.7.0
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
  coverage: ^1.9.2

flutter:
  uses-material-design: true
  generate: true
  
  # assets:
  #   - images/
  
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700